// Copies the EVM contracts' ABIs, and the bytecode the console deploys, from
// Foundry's build output into the app.
//
//   (cd ../evm && forge build) && node scripts/evm-abi.mjs
//
// Writes src/lib/evm/abi.ts and src/lib/evm/bytecode.ts. Generated, never edited.
import { readFileSync, writeFileSync } from "node:fs";

const out = (name) => JSON.parse(readFileSync(new URL(`../../evm/out/${name}.sol/${name}.json`, import.meta.url), "utf8"));
const contracts = ["Registry", "Servicer", "ServicedToken", "Directory", "TestUSD"];
const deployable = ["Registry", "Servicer"];

const header = "// Generated by scripts/evm-abi.mjs from ../evm (forge build). Do not edit.\n";
const abi = contracts.map((c) => `export const ${c[0].toLowerCase()}${c.slice(1)}Abi = ${JSON.stringify(out(c).abi)} as const;\n`);
writeFileSync(new URL("../src/lib/evm/abi.ts", import.meta.url), header + abi.join("\n"));

const bytecode = deployable.map((c) => `export const ${c[0].toLowerCase()}${c.slice(1)}Bytecode = "${out(c).bytecode.object}" as const;\n`);
writeFileSync(new URL("../src/lib/evm/bytecode.ts", import.meta.url), header + bytecode.join("\n"));
console.log(`abi.ts: ${contracts.join(", ")}; bytecode.ts: ${deployable.join(", ")}`);
